#r "System.Threading.dll"
#r "System.Text.RegularExpressions.dll"
#r "../../packages/NUnit/lib/nunit.framework.dll"
#r "../fable/Fable.Core/npm/Fable.Core.dll"
#r "DllRef/bin/Fable.Tests.DllRef.dll"
#load "Util/Util.fs"
      "Util/Util2.fs"
      "../tests_external/Util3.fs"
      "ArithmeticTests.fs"
      "ArrayTests.fs"
      "AsyncTests.fs"
      "ComparisonTests.fs"
      "DateTimeTests.fs"
      "DictionaryTests.fs"
      "EnumTests.fs"
      "ListTests.fs"
      "MapTests.fs"
      "MiscTests.fs"
      "ObservableTests.fs"
      "RecordTypeTests.fs"
      "RegexTests.fs"
      "ResizeArrayTests.fs"
      "SeqExpressionTests.fs"
      "SeqTests.fs"
      "SetTests.fs"
      "HashSetTests.fs"
      "StringTests.fs"
      "TupleTypeTests.fs"
      "UnionTypeTests.fs"
      "TypeTests.fs"
      "EventTests.fs"
      "SudokuTest.fs"
