from .array_ import Array
from .core import int32
from .option import Option
from .protocols import IEnumerable_1

class FSharpList[T](IEnumerable_1[T]):
    head_: T | None
    tail_: FSharpList[T] | None

def of_array[T](xs: Array[T]) -> FSharpList[T]: ...
def length[T](xs: FSharpList[T]) -> int: ...
def try_head[T](xs: FSharpList[T]) -> Option[T]: ...
def try_item[T](n: int32, xs: FSharpList[T]) -> Option[T]: ...
