// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("0.7.10")>]
[<assembly: AssemblyMetadataAttribute("fableCoreVersion","0.7.9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "0.7.10"
    let [<Literal>] AssemblyMetadata_fableCoreVersion = "0.7.9"
