from typing import final

@final
class Uint8:
    def __init__(self, value: int) -> None: ...
    def __add__(self, other: Uint8) -> Uint8: ...
    def __sub__(self, other: Uint8) -> Uint8: ...
    def __mul__(self, other: Uint8) -> Uint8: ...
    def __truediv__(self, other: Uint8) -> Uint8: ...
    def __mod__(self, other: Uint8) -> Uint8: ...
    def __neg__(self) -> Uint8: ...
    def __eq__(self, other: Uint8) -> bool: ...
    def __ne__(self, other: Uint8) -> bool: ...
    def __lt__(self, other: Uint8) -> bool: ...
    def __le__(self, other: Uint8) -> bool: ...
    def __gt__(self, other: Uint8) -> bool: ...
    def __ge__(self, other: Uint8) -> bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class Int8:
    def __init__(self, value: int) -> None: ...

@final
class UInt16:
    def __init__(self, value: int) -> None: ...

@final
class Int16:
    def __init__(self, value: int) -> None: ...

def sum_as_string(a: int, b: int) -> int: ...
