from collections.abc import Callable
from typing import overload

class FSharpRef[T]:
    @overload
    def __init__(self, contents_or_getter: T) -> None: ...
    @overload
    def __init__(self, contents_or_getter: Callable[[], T], setter: Callable[[T], None]) -> None: ...
    @property
    def contents(self) -> T: ...
    @contents.setter
    def contents(self, value: T) -> None: ...
