from collections.abc import Callable

class FSharpRef[T]:
    def __init__(self, contents_or_getter: T | Callable[[], T], setter: Callable[[T], None] | None = None) -> None: ...
    @property
    def contents(self) -> T: ...
    @contents.setter
    def contents(self, value: T) -> None: ...
