/** Declaration file generated by dts-gen */

export type FableOptions = {
    define?: string[],
    plugins?: string[],
    fableCore?: string,
    typedArrays?: boolean,
    clampByteArrays?: boolean,
    babel?: any
    extra?: any,
};

export function resolveBabelOptions(opts: any): any;

export function validateFableOptions(opts: FableOptions): void;

export namespace babelPlugins {
    function getRemoveUnneededNulls(): any;
    function getTransformMacroExpressions(babelTemplate: any): any;
}

export namespace client {
    function getFreePort(port?: number): number;
    function send(port: number, msg: string): Promise<string>;
}
