// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("0.7.43")>]
[<assembly: AssemblyMetadataAttribute("fableCoreVersion","0.7.28")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "0.7.43"
    let [<Literal>] AssemblyMetadata_fableCoreVersion = "0.7.28"
