import { FSharpRef } from "./Types.js";
import { IDateTime, DateKind } from "./Util.js";
export declare function fromUnixMilliseconds(value: number): IDateTime;
export declare function create(year: number, month: number, day: number): IDateTime;
export declare function maxValue(): IDateTime;
export declare function minValue(): IDateTime;
export declare function dayNumber(d: IDateTime): number;
export declare function fromDayNumber(dayNumber: number): IDateTime;
export declare function fromDateTime(d: IDateTime): IDateTime;
export declare function day(d: IDateTime): number;
export declare function month(d: IDateTime): number;
export declare function year(d: IDateTime): number;
export declare function dayOfWeek(d: IDateTime): number;
export declare function dayOfYear(d: IDateTime): number;
export declare function toDateTime(d: IDateTime, time: number, kind?: DateKind): IDateTime;
export declare function toString(d: IDateTime, format?: string, _provider?: any): string;
export declare function parse(str: string): IDateTime;
export declare function tryParse(v: string, defValue: FSharpRef<IDateTime>): boolean;
