import { FSharpRef } from "./Types.js";
export declare function tryParse(str: string, defValue: FSharpRef<number>): boolean;
export declare function parse(str: string): number;
export declare function isPositiveInfinity(x: number): boolean;
export declare function isNegativeInfinity(x: number): boolean;
export declare function isInfinity(x: number): boolean;
export declare function max(x: number, y: number): number;
export declare function min(x: number, y: number): number;
export declare function maxMagnitude(x: number, y: number): number;
export declare function minMagnitude(x: number, y: number): number;
export declare function clamp(x: number, min: number, max: number): number;
