import { FSharpRef } from "./Types.js";
import { IDateTime } from "./Util.js";
export declare function create(h?: number, m?: number, s?: number, ms?: number): number;
export declare function fromTicks(ticks: number | bigint): number;
export declare function fromTimeSpan(timeSpan: number): number;
export declare function fromDateTime(d: IDateTime): number;
export declare function maxValue(): number;
export declare function add(t: number, ts: number, wrappedDays?: FSharpRef<number>): number;
export declare function addHours(t: number, h: number): number;
export declare function addMinutes(t: number, m: number): number;
export declare function isBetween(t: number, start: number, end: number): boolean;
export declare function toString(t: number, format?: string, _provider?: any): string;
export declare function parse(str: string): number;
export declare function tryParse(v: string, defValue: FSharpRef<number>): boolean;
export declare function op_Subtraction(left: number, right: number): number;
